# Generated by Django 4.1.3 on 2022-12-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_dislike_product_like_product_rate_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rate', to='home.product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
