# Generated by Django 4.1.3 on 2022-12-17 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_rename_peoduct_image_images_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='fa_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
