# Generated by Django 4.1.3 on 2022-12-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Both',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('size_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'none'), ('Color', 'color'), ('Size', 'size'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='both_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.both'),
        ),
    ]
