# Generated by Django 4.1.3 on 2022-12-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_both_alter_product_status_variant_both_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='both_variant',
        ),
        migrations.DeleteModel(
            name='Both',
        ),
    ]
